
  CREATE TABLE "PROYECTOBD2"."BITACORACHEQUE" 
   (	"IDBITÁCORA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"FECHA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IDCLLIENTEFK" NUMBER(*,0) NOT NULL ENABLE, 
	"IDCHEQUEFK" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "BITACORACHEQUE_PK" PRIMARY KEY ("IDBITÁCORA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKCHEQUECLIENTE" FOREIGN KEY ("IDCLLIENTEFK")
	  REFERENCES "PROYECTOBD2"."USUARIO" ("IDUSUARIO") ENABLE, 
	 CONSTRAINT "FKCHEQUECHEQUE" FOREIGN KEY ("IDCHEQUEFK")
	  REFERENCES "PROYECTOBD2"."CHEQUE" ("IDCHEQUE") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;






-------
CREATE TABLE "PROYECTOBD2"."CHEQUE" 
   (	"IDCHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHAEMISION" DATE NOT NULL ENABLE, 
	"MONTO" FLOAT(126) NOT NULL ENABLE, 
	"IDCHEQUERAFK" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CHEQUE_PK" PRIMARY KEY ("IDCHEQUE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKCHEQUECHEQUERA" FOREIGN KEY ("IDCHEQUERAFK")
	  REFERENCES "PROYECTOBD2"."CHEQUERA" ("IDCHEQUERA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  
------


CREATE TABLE "PROYECTOBD2"."CHEQUERA" 
   (	"IDCHEQUERA" NUMBER(*,0) NOT NULL ENABLE, 
	"FECHAEMISION" DATE NOT NULL ENABLE, 
	"CHEQUESORIGINALES" NUMBER(*,0) NOT NULL ENABLE, 
	"CHEQUESACTUALES" NUMBER(*,0) NOT NULL ENABLE, 
	"IDCUENTAFK" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CHEQUERA_PK" PRIMARY KEY ("IDCHEQUERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FKCHEQUERACUENTA" FOREIGN KEY ("IDCUENTAFK")
	  REFERENCES "PROYECTOBD2"."CUENTABANCO" ("IDCUENTA") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

 

-------

CREATE TABLE "PROYECTOBD2"."CUENTABANCO" 
   (	"IDCUENTA" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBREBANCO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMISION" DATE NOT NULL ENABLE, 
	"MONTOORIGEN" FLOAT(126) NOT NULL ENABLE, 
	"MONTOACTUAL" FLOAT(126) NOT NULL ENABLE, 
	 CONSTRAINT "CUENTABANCO_PK" PRIMARY KEY ("IDCUENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

  

-------
 CREATE TABLE "PROYECTOBD2"."USUARIO" 
   (	"IDUSUARIO" NUMBER(*,0) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"APELLIDO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"DIRECCION" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ROLSISTEMA" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MONTOAPROBADO" NUMBER(*,0) NOT NULL ENABLE, 
	"USUARIO" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PSSWRD" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "USUARIO_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


--










